import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import {
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import Providers from './providers'
import Link from 'next/link'
import { Button } from '@/components/ui/button'
import GuestPicker from './GuestPicker'
import { Suspense } from 'react'
import { Spinner } from '@/components/ui/spinner'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-orange-50 flex flex-col min-h-dvh items-center`}
      >
        <Suspense fallback={<Spinner className="h-dvh" />}>
          <Providers>
            <header className="sticky z-10 top-0 w-full gap-2 p-2 px-4 h-13 flex flex-row items-center border-b bg-orange-50 shadow-lg">
              <Link href="/" className="text-lg font-extrabold text-primary">
                ROS
              </Link>
              <span className="flex-1" />
              <SignedOut>
                <GuestPicker />
                <SignInButton>
                  <Button variant="outlineColored">Sign In</Button>
                </SignInButton>
                <SignUpButton>
                  <Button variant="default">Sign Up</Button>
                </SignUpButton>
              </SignedOut>
              <SignedIn>
                <UserButton showName />
              </SignedIn>
            </header>
            <div className="w-full max-w-xl flex-1 flex flex-col items-center pb-16">
              {children}
            </div>
          </Providers>
        </Suspense>
      </body>
    </html>
  )
}
